[server]
host = "0.0.0.0"
port = 8080

[rabbitmq]
server = "amqp://guest:guest@127.0.0.1:5672/"
queue1 = "waf_to_ml"
queue2 = "ml_to_waf"

[[websites]]
name = "example"
api = "/api"
url = "http://127.0.0.1:8081"

[[rules]]
name = "SQL Injection"
regex = ".*?(select|union|insert|update|delete|drop|alter|create|database|table|grant|exec|execute|xp_cmdshell|sp_oacreate|sp_oamethod|sp_addextendedproc|sp_addlinkedserver|sp_addlinkedsrvlogin|sp_addtype|sp_addserver|sp_addremotelogin|sp_addrolemember|sp_addrole|sp_addapprole|sp_addalias|sp_adduser|sp_addlogin|sp_addgroup|sp_addextendedproperty|sp_addmessage"